default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username : glen
  password : dset

development:
  <<: *default
  database: cardDB

test:
  <<: *default
  database: cardDB

production:
  <<: *default
  database: cardDB
